name: Fixtures

on:
  push:
    branches: [ main ]
  schedule:
  - cron: "0 13-23 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up cargo & curl
      run: sudo apt install -y curl cargo
      
    - name: Set up hq
      run: cargo install html-query

    - name: Generate Dungourney ECB Fixtures
      run: /bin/bash dg.sh
      
