name: Fixtures

on:
  push:
    branches: [ main ]
  schedule:
  - cron: "0 23 * * *"

permissions:
  contents: write  # Required for pushing to gh-pages
  pages: write     # Required for deploying to GitHub Pages

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Set up cargo & curl
        run: sudo apt install -y curl cargo jq
      
      - name: Set up hq
        run: cargo install html-query

      - name: Generate Fixtures
        run: |
          /bin/bash dg.sh > docs/dg.json
          /bin/bash dg_gaa.sh > docs/dg_gaa.json
          /bin/bash kog.sh > docs/kog.json
          echo "Hi" > docs/index.html

      - name: Copy HTML
        run: |
          cp html/* docs/

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        run: |
          git checkout --orphan gh-pages
          git reset --hard
          git add docs/
          git commit -m "Deploy json to GitHub Pages"
          git push -f origin gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}          