name: Fixtures

on:
  push:
    branches: [ main ]
  schedule:
  - cron: "0 23 * * *"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up cargo & curl
      run: sudo apt install -y curl cargo jq
      
    - name: Set up hq
      run: cargo install html-query

    - name: Generate Fixtures
      run: |
        /bin/bash dg.sh > docs/gg.json
        /bin/bash dg_gaa.sh > docs/dg_gaa.json
        /bin/bash kog.sh > docs/kog.json

    - name: Deploy Page
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Commit & Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add docs/gg.json -f
          git add docs/dg_gaa.json -f
          git add docs/kog.json -f
          git commit -m "Update docs" -a
          git fetch origin
          git rebase --strategy-option=theirs origin/main
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}          